apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: node:14
        command: ["node", "-e", "require('http').createServer((req,res)=>res.end('Hello from my-app!')).listen(3000)"]
        ports:
        - containerPort: 3000
